### ISSUE TITLE
FE Selection CUI only not working in production

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1458]
This needs to be fixed ASAP!
Especially since liteloader is incompatible with current forge so installing WE-CUI is a no-option.

**Comment by Mumfrey** [comment]
If LiteLoader is incompatible with Forge it would be lovely if people would actually tell me so that I can ... you know ... fix it.

**Comment by olee** [comment]
Oh you made it? Well I didn't know until yesterday, too.
I tried it a few times but it only loaded liteloader for me with a very old forge build.

**Comment by olee** [comment]
Here is the log: https://gist.github.com/olee/2b92afa197ced75a879c

**Comment by Mumfrey** [comment]
That looks like a conflicting version of guava. It's possible that FML for 1.7.10 has updated to a newer version of guava than the version which shipped with 1.7.10. You should be able to work around this easily by just extracting the liteloader jar to the `mods/1.7.10` folder and then launching forge instead of "extending" liteloader from the forge version. Follow [the instructions here](http://docs.liteloader.com/user:install:forge#mod)

**Comment by olee** [comment]
Ah that is good to know and I was not able to find that information anywhere (so that's what this 1.7.10 folder is used for....).

As that liteloader (side) issue was solved now, we at FE still need to figure out why the CUI only works in dev environment (probably some network issue again :weary:)

**Comment by olee** [comment]
@Mumfrey Ok trying to put it in 1.7.10 folder does not seem to solve the loading issue.
If possible, I would like to talk to you about this on IRC or move this issue over to liteloader's issue tracker (wherever it is)

**Comment by Mumfrey** [comment]
LiteLoader's issue tracker is [on Assembla](https://www.assembla.com/spaces/liteloader/support/tickets). I suspect that if having FML load liteloader doesn't fix the issue then the version of Guava used by LiteLoader will need to be updated.

**Comment by olee** [comment]
Issue with liteloader moved over to https://www.assembla.com/spaces/liteloader/support/tickets/76

**Comment by liach** [comment]
@olee Is the newest one in 1.7.10-ls compatible?

**Comment by luacs1998** [comment]
@olee claims it started working for him one say, thus invalidating this issue. Closing.

**Comment by olee** [comment]
Found out the problem:
FE's net messages do not seem to work any more, if both client and server mod are present at the same time.
This should be fixed so FE can be used in singleplayer as well (e.g. for adventure maps).

**Comment by olee** [comment]
See issue https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1525

**Comment by luacs1998** [comment]
This issue is back...

This time, it seems like the packets aren't being received again. @olee can you check your theory about null-handlers?

**Comment by olee** [comment]
Fixed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/896a5eb6a709d17f0b5eef04b94313708a48fcf1
This was a weird issue.
The packet did not get to the sender if sent in PlayerLoggedInEvent.
However once I placed a breakpoint on the event, it worked.
So I just delayed sending the message to the first client tick event.

**Comment by luacs1998** [comment]
Thanks.
